# Use root/example as user/password credentials
version: "3.1"

services:
  api_products:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mario
      - DB_NAME=mariodb
      - DB_PORT=3306
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: mario
      MYSQL_PASSWORD: mario
      MYSQL_DATABASE: mariodb

volumes:
  mysql-data:
